# from vgamepad import XUSB_BUTTON
from enum import Enum, IntFlag
from typing import Union


# max_xusb = max(XUSB_BUTTON)


class GamepadControl(str, Enum):
    LEFT_TRIGGER = "LEFT_TRIGGER"
    RIGHT_TRIGGER = "RIGHT_TRIGGER"
    LEFT_JOYSTICK_X = "LEFT_JOYSTICK_X"
    LEFT_JOYSTICK_Y = "LEFT_JOYSTICK_Y"
    RIGHT_JOYSTICK_X = "RIGHT_JOYSTICK_X"
    RIGHT_JOYSTICK_Y = "RIGHT_JOYSTICK_Y"


class GamepadButton(str, Enum):
    XUSB_GAMEPAD_DPAD_UP = "XUSB_GAMEPAD_DPAD_UP"
    XUSB_GAMEPAD_DPAD_DOWN = "XUSB_GAMEPAD_DPAD_DOWN"
    XUSB_GAMEPAD_DPAD_LEFT = "XUSB_GAMEPAD_DPAD_LEFT"
    XUSB_GAMEPAD_DPAD_RIGHT = "XUSB_GAMEPAD_DPAD_RIGHT"
    XUSB_GAMEPAD_START = "XUSB_GAMEPAD_START"
    XUSB_GAMEPAD_BACK = "XUSB_GAMEPAD_BACK"
    XUSB_GAMEPAD_LEFT_THUMB = "XUSB_GAMEPAD_LEFT_THUMB"
    XUSB_GAMEPAD_RIGHT_THUMB = "XUSB_GAMEPAD_RIGHT_THUMB"
    XUSB_GAMEPAD_LEFT_SHOULDER = "XUSB_GAMEPAD_LEFT_SHOULDER"
    XUSB_GAMEPAD_RIGHT_SHOULDER = "XUSB_GAMEPAD_RIGHT_SHOULDER"
    XUSB_GAMEPAD_GUIDE = "XUSB_GAMEPAD_GUIDE"
    XUSB_GAMEPAD_A = "XUSB_GAMEPAD_A"
    XUSB_GAMEPAD_B = "XUSB_GAMEPAD_B"
    XUSB_GAMEPAD_X = "XUSB_GAMEPAD_X"
    XUSB_GAMEPAD_Y = "XUSB_GAMEPAD_Y"


GamepadAction = Union[GamepadControl, GamepadButton]
